[package]
name = "chela"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fill_f32"
path = "benches/fill_f32.rs"

[[bin]]
name = "ones_f32"
path = "benches/ones_f32.rs"


[dependencies]
cpu-time = "1.0.0"
bitflags = "2.6.0"

[lints.rust]
private_bounds = "allow"
dead_code = "allow"
