[package]
name = "chela"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "fill_f32"
path = "benches/fill_f32.rs"

[[bin]]
name = "fill_f32_slice"
path = "benches/fill_f32_slice.rs"

[[bin]]
name = "ones_f32"
path = "benches/ones_f32.rs"

[[bin]]
name = "sum_f32"
path = "benches/sum_f32.rs"

[[bin]]
name = "sum_f32_slice"
path = "benches/sum_f32_slice.rs"

[[bin]]
name = "sum_f32_slice2"
path = "benches/sum_f32_slice2.rs"


[dependencies]
cpu-time = "1.0.0"
bitflags = "2.6.0"
num = "0.4.3"
rand = "0.8.5"
rand_distr = "0.4"

[lints.rust]
private_bounds = "allow"
dead_code = "allow"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(use_apple_accelerate)'] }

[profile.release]
debug = true
strip = false

[features]
default = []
apple_accelerate = []
