[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))']
rustflags = [
        "--cfg", "apple_accelerate",
        "--cfg", "apple_vdsp",
        "--cfg", "blas",
        "--cfg", "neon_simd"
]

[build]
rustflags = ["-Ctarget-cpu=native"]
