name: Rust Build & Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - src/**
      - test/**
      - Cargo.toml
      
  pull_request:
    branches: [ "master" ]
    paths:
      - src/**
      - test/**
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
